### ISSUE TITLE
代码更新

### ISSUE THREAD

**Issue by WatsonWangZh** [Witt-Wang/oneshot#1]
请问可以更新一下代码，提供一下运行指南吗？不然这个开源没有什么意义啊。

**Comment by Witt-Wang** [comment]
您好，因为假期原因，并且当时研究不充分，受限于数据数据集的提取，论文所提出sense graph的one shot 比较狭隘，继续改进价值不大，为了进行真正的one shot，我们在期刊版本使用别的数据集，重新进行代码改进，工作完成后，节后会进行一并更新。如果您有什么其他疑问，可以联系 wangweitao@seu.edu.cn 。
